### ISSUE TITLE
[Bug]: CTD when reloading a save while in combat after registering a combatState event

### ISSUE THREAD

**Issue by oto-git** [skyrim-multiplayer/skymp#1544]
### Severity

Critical. A critical defect that causes some key functionality to fail.

### Priority

High. Anything that impacts the typical user flow or blocks app usage.

### Description

If a combatState event was registered, I observed a CTD when reloading a save before the NPC appeared during a fight with an NPC after a hostile random NPC appeared.
(The CTD did not occur if the save was reloaded after the battle with the NPC ended.)

NetScriptFramework Crash Log: https://drive.google.com/file/d/1YL84AYcA02xc0-5l5rfdpi_jHf1ELcVQ/view?usp=sharing

https://github.com/skyrim-multiplayer/skymp/issues/1305
https://github.com/skyrim-multiplayer/skymp/issues/1540
The phenomenon is similar to the save reload CTD reported elsewhere.

Even if the combatState event registration was canceled at the time the preLoadGame event occurred, a CTD would still occur, and the CTD could not be prevented unless the event registration was canceled at the time before the preLoadGame event occurred.
Also, loading a save saved from the menu before the NPC appeared caused a CTD, but loading a save saved by pressing F5 did not.
(F5 saves are set to regular saves instead of quick saves in the SSE Engine Fixes configuration file.)

### OS

Windows

### OS version

10

### Skyrim version

1.5.97.0.8

### SKSE version

2.0.20

### client commit''s hash

None

### server commit''s hash

None

### Videocard model

Radeon RX 590

### Steps to reproduce

With the combatState event registered, perform the following steps.

1. Save from the system menu by pressing ESC, either externally or internally. (Do not press F5 to save).
2. Type "player.placeatme 0001bcd8 5" in the console and a random NPC will appear. (They are bandits, so they will be hostile as they appear.)
3. Reload the save for step 1 after confirming that the bandits have been hostile.

### Expected result

No crashes after loading the save.

### Actual result

The game crashes as soon as the loading completes.

**Comment by objir** [comment]
A working fix following the example of the fix for #1305:

In EventHandler.cpp, edit "Line 243-266" to:
`EventResult EventHandler::ProcessEvent(const RE::TESCombatEvent* event,
                                       RE::BSTEventSource<RE::TESCombatEvent>*)
{
  if (!event) {
    return EventResult::kContinue;
  }

  auto target = event->targetActor.get();
  auto actor = event->actor.get();

  if (!target || !actor) {
    return EventResult::kContinue;
  }

  auto targetid = target->GetFormID();
  auto actorid = actor->GetFormID();

  auto isCombat = event->newState.any(RE::ACTOR_COMBAT_STATE::kCombat);
  auto isSearching = event->newState.any(RE::ACTOR_COMBAT_STATE::kSearching);

  SkyrimPlatform::GetSingleton()->AddUpdateTask([targetid, actorid, isCombat, isSearching] {
    auto obj = JsValue::Object();

    auto target = RE::TESForm::LookupByID<RE::TESObjectREFR>(targetid);
    auto actor = RE::TESForm::LookupByID<RE::TESObjectREFR>(actorid);

    AddObjProperty(&obj, "target", target, "ObjectReference");
    AddObjProperty(&obj, "actor", actor, "ObjectReference");
    AddObjProperty(&obj, "isCombat",
                   isCombat);
    AddObjProperty(&obj, "isSearching",
                   isSearching);

    SendEvent("combatState", obj);
  });

  return EventResult::kContinue;
}`

JS plugin I used for testing:
`import { Actor, on, printConsole } from "@skyrim-platform/skyrim-platform"

on('combatState', (event) => {
    printConsole("combatState changed")
    let a = Actor.from(event.actor)
    let t = Actor.from(event.target)
    if((a && a!.getBaseObject()!.getFormID() == 110808) || (t && t!.getBaseObject()!.getFormID() == 110808)){
        printConsole("Bandit Chief combatState changed:" + " isCombat: " + event.isCombat + ", " + "isSearching: " + event.isSearching + ".")
    }
});`

Console Command used: 'player.placeatme 1bcd8 1'

Crashes are gone and the event appears working correctly:
[img]https://i.imgur.com/66hJBg5.png[/img]

**Comment by Pospelove** [comment]
@objir Impressive! Could you please submit a PR?

**Comment by objir** [comment]
#1551
