### ISSUE TITLE
Speed up calls of scripting functions

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#508]
In [SkyrimPlatformProxy.cpp](https://github.com/skyrim-multiplayer/skymp/blob/main/skyrim-platform/src/platform_se/skyrim_platform/SkyrimPlatformProxy.cpp#L99) we call scripting function by name and class name:

```c++
thread_local auto callNative = origin.GetProperty("callNative");
return callNative.Call(*callNativeArgs);
```

The existing code is pretty slow since it goes into JS engine internals under the hood. Since we are in C++ code we should use C++ API for calling scripting functions instead: [CallNative.h.](https://github.com/skyrim-multiplayer/skymp/blob/main/skyrim-platform/src/platform_se/skyrim_platform/CallNative.h#L67)

Example of using CallNative.h is in [CallNativeApi.cpp](https://github.com/skyrim-multiplayer/skymp/blob/main/skyrim-platform/src/platform_se/skyrim_platform/CallNativeApi.cpp#L36)

Feel free to refactor anything but consider generating as low diff as possible.

Here is benchmark:
```js
// Save this code as "Data/Platform/Plugins/test.js"
// Ping kkEngine or RetroWave or Pospelov in Discord if this code isn't working 
skyrimPlatform.on("update", () => {
    let date = Date.now();
    for (let i = 0; i < 10000; ++i) skyrimPlatform.Game.getSunPositionX();
    skyrimPlatform.printConsole("SP:", Date.now() - date);
});
```
it outputs to the game console (can be opened by ~).

Please provide "before" and "after" benchmark results. I think that performance will be better after doing this task, but it's ok if the actual results will be not so much better.

**Comment by Pospelove** [comment]
@Wedmer Hey! Any progress on this?

**Comment by ZikkeyLS** [comment]
![Initial](https://github.com/skyrim-multiplayer/skymp/assets/68398139/f74205d1-1e7a-4595-8652-6948405f723d)
![Version01](https://github.com/skyrim-multiplayer/skymp/assets/68398139/33f0c8f0-aa7b-48ef-83d0-51f0bcbe93f0)

_Initial ⇾ Result_

**Comparison**:
Initial - min: 226 ms; max: 258 ms; average (middle of all current): **~238 ms**
Result of #1491 - min: 212 ms; max: 258 ms; average (middle of all current): **~218 ms**
Perhaps the maximum is the same because of the same time period when the game starts loading. (it can be ~250-260 ms)

**Benchmark code**:
```JavaScript
// Save this code as "Data/Platform/Plugins/test.js"
// Ping kkEngine or RetroWave or Pospelov in Discord if this code isn't working

let min = 10000
let max = 0

skyrimPlatform.on("update", () => {
    let date = Date.now();
    for (let i = 0; i < 10000; ++i) skyrimPlatform.Game.getSunPositionX();

    let current = Date.now() - date;
    if (current < min) min = current;
    else if (current > max) max = current;

    skyrimPlatform.printConsole("SP - min: ", min, " max: ", max, " current: ", current);
});
```

**Benchmark device configurations**:
OS - Windows 10 Pro
Processor - Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.90 GHz
RAM memory - 32GB
Video card - NVIDIA GeForce GTX 1050TI

**Comment by Pospelove** [comment]
Thank you for your detailed report and for your PR @ZikkeyLS, taking a look
