### ISSUE TITLE
Support Skyrim AE

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#554]
Depends on #538

**Comment by mrowrpurr** [comment]
### More context below on what the TODO is here (provided by @Pospelove)

----

- Need to update addresses here:
  > https://github.com/skyrim-multiplayer/skymp/blob/main/skyrim-platform/src/platform_se/skyrim_platform/FridaHooks.cpp#L101

- Fix smth here too: maybe
  > https://github.com/skyrim-multiplayer/skymp/tree/main/skyrim-platform/src/tilted/hooks

### _Various Notes_

SP doesn't compile with latest CommonLibSSE

P.S. there is an abandoned PR from Oct 1 that updates CommonLibSSE https://github.com/skyrim-multiplayer/skymp/pull/272

P.S.S. Now SkyrimPlatform relies on CommonLibSSE + SKSE hardly, but 1) dependencies keep changing 2) SP could support more games: Skyrim SE, Skyrim AE. And in the future... Skyrim VR? Fallout 4? OpenMW? SkyMP server? Starfield? TES 6?..

NodeJS has node-addon-api, a stable API for C++ modules as a replacement of V8 API that keeps changing.
We need something similar. A single interface that we control to depend SP on. And implementations for SE and AE.

But how to fix the whole codebase? I think the best way to disable CommonLibSSE at all and see where compilation errors occur.

Then use... let's name this SPGameInterface for example. instead of using CommonLibSSE directly

Everything links to skyrim_platform here: https://github.com/skyrim-multiplayer/skymp/blob/67bb639a2525e4bd193b9b704b86d430653a34c9/cmake/link_vcpkg_dependencies.cmake#L27
changing to if (FALSE) would disable commonlibsse/skse in project

**Comment by Pospelove** [comment]
Fixed in main branch
