### ISSUE TITLE
SkyrimPlatform breaks savegames

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#796]
> 17 January 2022, 7:58AM
For some reason, since installing 2.5.0, saving will take twice as much time, and end up creating a corrupted save which is impossible to reload. File size is much smaller, almost half the size, and it doesn't save an .SKSE file. Reverting back to 2.4.0 fixes the issue.
EDIT: Judging from someone else's report, it seems 2.5.0 might be broken for some users (so far only two reports), so as a warning and recommendation
DO NOT UPGRADE to 2.5.0 until further notice from mod author.

> 17 January 2022, 8:12AM
For the love of god, put a game break warning on this mod. DO NOT UPDATE ON A CURRENT SAVE. It looks like this requires a new game when updating versions. If you update on a current save it corrupts the save. Also, when you update this mod, saving takes 10 times longer then normal.
Quick saving now takes 30 seconds alongside corrupted saves. This same issue happened on the previous update as well.

**Comment by objir** [comment]
I am stilling using 2.5.0 since upgrading from 2.4.0 and I can make saves without issues.

I do believe this is just an issue of mod installation. I am using vortex and it couldn't unpack the mod archive but still showed that the mod is "enabled", while the mod files are not installed at all. I ended up mannually unpack the archive to mod staging folder and intalled it without a problem.

**Comment by Pospelove** [comment]
@objir Does upgrade work for you? Even without starting a new game?

**Comment by objir** [comment]
Yes and yes.

**Comment by duffbeeeer** [comment]
I have tested this on this https://modwat.ch/u/DuffB LO and cant get any save corruption either.

**Comment by duffbeeeer** [comment]
I got hands on some logs from a user who is experiencing save corruption but also a lot more issue regarding 2.5.0:

`In addition to the dialogue 2 other issues that may be unrelated but I will mention in case this comes from others. Can only use keyboard, not controller with auto input switch. Using controller works fine but certain functions cause a crash - selecting play instrument from bards reborn. 100% crash with controller plugged in and none without. 2nd is eventually first person couldn't move head, but that may be a sympton of the corrupt save game rather than cause. When starting a new game head was working, but all other issues persisted.`

[loadorder.txt](https://github.com/skyrim-multiplayer/skymp/files/7969900/loadorder.txt)
[Crash_2022_1_27_20-58-18.txt](https://github.com/skyrim-multiplayer/skymp/files/7969904/Crash_2022_1_27_20-58-18.txt)
[Crash_2022_1_26_23-46-56.txt](https://github.com/skyrim-multiplayer/skymp/files/7969906/Crash_2022_1_26_23-46-56.txt)

There is more crashlogs like this but something seems to be wrong with ConsoleUitlSSE?

**Comment by Pospelove** [comment]
@duffbeeeer Hm. Theoretically, there could be incompatibility between SP and ConsoleUtilSSE. Is it reproduceable without ConsoleUtil?

**Comment by duffbeeeer** [comment]
@Pospelove They user will test this later tonight. 

Are any SKSE log files helpful like skse64.log?

**Comment by Pospelove** [comment]
@duffbeeeer Not really

**Comment by Pospelove** [comment]
Honestly IDK how do I debug that

**Comment by Pospelove** [comment]
@duffbeeeer I think we need a reproducible mod setup. I.e. wabbajack modlist. It could help with testing.

**Comment by duffbeeeer** [comment]
@Pospelove so we create a list based on the load ordder i posted?  

https://github.com/wabbajack-tools/wabbajack#creating-your-own-modlist

**Comment by Pospelove** [comment]
@duffbeeeer Well let's do it

**Comment by duffbeeeer** [comment]
@Pospelove  idlike to suggest we hold out on the AE update for SP first. Maybe this problem disappears anyway because if different binaries?

**Comment by Pospelove** [comment]
Closing for now... I have some ideas on fixing this but this issue probably doesn't help

**Comment by Pospelove** [comment]
created follow-up issue https://github.com/skyrim-multiplayer/skymp/issues/1956
